language: rust
sudo: false
cache: cargo
rust:
  - nightly

matrix:
  fast_finish: true

  include:
    - name: "release"
      script:
        - cargo build --all --release
        - cargo test --all --release

script:
- cargo build --all 
- cargo test --all 
